title = "James Millner"

[author]
name = "James Millner"
image = "img/avatar.jpg"
headline = "A motivated Software Engineer based in Huddersfield, United Kingdom"
bio = "Software Engineer @ 10xBanking"
links = [
  { twitter = "https://twitter.com/_jamesmillner" },
  { youtube = "https://www.youtube.com/channel/UCNLK4hRA46Oe21VKoXweM-A/featured" },
  { strava = "https://www.strava.com/athletes/james_millner" },
  { komoot = "https://www.komoot.com/user/813735907910?ref=wud" },
  { telegram = "https://t.me/JimmyMillner" },
  { github = "https://github.com/james-millner" },
  { linkedin = "https://www.linkedin.com/in/james-millner-26a7974a/" },
  { email = "mailto:hello@jamesmillner.dev" },
  { calendar = "https://cal.com/jamesmillner" },
]

[share-links-active]
  twitter = true
  linkedin = true