title = "James Millner"

languageCode = "en"
languageName = "English"
weight = 1

[languages]
[languages.en]
htmlCode = "en"
displayName = "EN"
rtl = false


[params.author]
name = "James Millner"
image = "img/avatar.jpg"
headline = "UK-based Software Engineer with a passion for cycling and fitness, based in Huddersfield, Yorkshire."
links = [
  { blueskyweb = "https://bsky.app/profile/jamesmillner.dev" },
  { x = "https://twitter.com/_jamesmillner" },
  { youtube = "https://www.youtube.com/@WestYorkshireCyclist" },
  { strava = "https://www.strava.com/athletes/james_millner" },
  { komoot = "https://www.komoot.com/user/813735907910?ref=wud" },
  { github = "https://github.com/james-millner" },
  { linkedin = "https://www.linkedin.com/in/%F0%9F%9A%B4%E2%80%8D%E2%99%82%EF%B8%8Fjames-millner-26a7974a" },
  { email = "mailto:hello@jamesmillner.dev" },
  { calendar = "https://cal.com/jamesmillner" }
]